version: 2
snapshot:
  widths:
    - 375
    - 768
    - 1280
  min-height: 1024
  percy-css: |
    * {
      animation: none !important;
      transition: none !important;
    }
static:
  cleanUrls: true
discovery:
  allowed-hostnames:
    - localhost
